### PR TITLE
add create binary resource test

### PR DESCRIPTION
**Pull request by aelkiss**
- uses RandomStringUtils from Apache Commons - creates random data
  at about 100MB/sec
- avoids creating fixtures on disk
- avoids creating compressible data

### CODE REVIEW

**Comment by awoods** [comment]
@aelkiss, in order for us to accept this PR, could you please return a signed CLA?
https://wiki.duraspace.org/display/DSP/Contributor+License+Agreements

**Comment by aelkiss** [comment]
Thanks -- I'll try to take care of this tomorrow.

**Comment by awoods** [comment]
@aelkiss, when I run the "Fedora4 Create Binary Resource" jmeter test, the binary resources are successfully created, but inspecting them within the Fedora HTML UI, I see that they all have size of 0 bytes. This is also confirmed when I download them.

I also have a question about the variables: `FILE_SIZE_STD_DEV` and `FILE_SIZE_MEAN` found in the "Set File Content" beanshell preprocessor script. Can you point me to where those variables are defined?

**Comment by aelkiss** [comment]
Curious. Are there any pre-processor errors logged? Possibly a failure to
find org.apache.commons.lang3.RandomStringUtils? This was in my classpath
by default (from Apache Commons) with jmeter from Debian Jessie, but maybe
in your set up it is not?

FILE_SIZE_STD_DEV and FILE_SIZE_MEAN should be defined at the top level
'Fedora Profiling' test plan node. There were some defaults there (easily
changed), probably a holdover from
https://github.com/fcrepo4-archive/ff-jmeter-madness, but still useful in
this context.

**Comment by awoods** [comment]
Thanks for the pointing me to the variable definitions.
As for errors in logs... none. Can you verify that binary resources are being created with non-zero size? @ruebot?

**Comment by aelkiss** [comment]
Yeah, something is definitely not right; I'm seeing the same behavior
(empty binary resources) now. I did some clean-up in between what I had
working and what I sent as a pull request -- I thought I had verified the
PR version was properly creating binary resources, but apparently not. Go
ahead and reject this PR, and I'll re-submit something that is working.
Sorry for wasting your time on this one.

**Comment by awoods** [comment]
Yes, as @ruebot suggested, it is preferred that you use the same PR with incremental commits based on code review comments.

**Comment by aelkiss** [comment]
Will do. I'll aim to submit corrections this afternoon or tomorrow morning.

**Comment by aelkiss** [comment]
I pushed an update; this version should actually be creating non-empty files. Additionally, I cleaned up the code to generate the file content -it now generates files between 10KB and 100KB as specified by https://wiki.duraspace.org/display/FF/Performance+and+Scalability+Test+Plans

**Comment by awoods** [comment]
Thanks, @aelkiss. 
FYI, we use GitHub comments for discussing specifics about a given PR, and JIRA for managing the workflow of the issue. Please move your JIRA ticket to "Start Review" if you are ready for this to move forward.
https://jira.duraspace.org/browse/FCREPO-1899

**Comment by aelkiss** [comment]
Thanks. I've updated the JIRA ticket.

**Comment by awoods** [comment]
@aelkiss, how exactly are you running your added `Fedora4 Create Binary Resource` capability?
I have pulled down your latest updates, then run:

```
<path/to>/jmeter -t fedora.jmx
```

Then, in the JMeter UI, I select your new `Fedora4 Create Binary Resource` thread-group and hit the "Start" button, which looks like a "Play" button. Resources are created, but are still of size 0-bytes? 
Suggestions?

**Comment by aelkiss** [comment]
I wonder if you have both the 'create new containers' and 'create binary
resource' tests enabled? If so it looks like it will first run the 'create
new containers' test, which will create all zero-byte resources.

Try the following:
- Disable the 'create new containers' test (right click, disable)
- Then start (the 'play' button)
- You should see non-empty resources in Fedora.

Aaron Elkiss
Library IT Core Services
University of Michigan

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo4-labs/fcrepo4-jmeter/commit/c30bbe3bd73bd2da977db5be879062b3dcb3ba7b

**Pull request closed without merging**
